apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.9, pipelines.kubeflow.org/pipeline_compilation_time: '2024-05-21T10:36:43.432053',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "A pipeline to demonstrate
      use of PersistentVolumeClaim", "inputs": [{"default": "/mnt/data/kubeflow",
      "name": "log", "optional": true}], "name": "Hello World"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.9}
spec:
  entrypoint: hello-world
  templates:
  - name: hello-world
    dag:
      tasks: []
  arguments:
    parameters:
    - {name: log, value: /mnt/data/kubeflow}
  serviceAccountName: pipeline-runner
