apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 20Gi
  storageClassName: local-path  
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/kubeflow"
---
apiVersion: v1  
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: kubeflow-user-example-com
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
